### PR TITLE
Add support for custom SSL socket factory and trust manager

### PR DESCRIPTION
**Pull request by lotr**

### CODE REVIEW

**Comment by lotr** [comment]
@DavidMealha @dvacca is this check failure caused somehow by my code? Cause I don't see any connection between this failure and my changes.

Just asking whether I need to do some more work to fix it or it's unrelated, so my PR is OK.

Thanks :)

**Comment by dvacca** [comment]
Hello @lotr,
We believe that failure is due to the fact that your PR is coming from a fork.
We've just checked in [PR#80](https://github.com/onfido/onfido-java/pull/80) that CI is working fine.

Would you mind creating a new PR directly from the main repository?

Thanks.

Kind regards.
Davide

**Comment by lotr** [comment]
@dvacca I'm little bit confused now... from the README:
>Contributing
Fork it (https://github.com/onfido/onfido-java/fork)
Create your feature branch (git checkout -b my-new-feature)
Make your changes, see below sections for project setup and testing.

Btw I've tried to push to this repo, but I'm not allowed, so the only option in the end was the fork

**Comment by dvacca** [comment]
@lotr I apologize for the bad advice, you're definitively right.

I've created [PR#80](https://github.com/onfido/onfido-java/pull/80) which should solve the issue you're experiencing. I'll let you know as soon as it's merged.

**Comment by lotr** [comment]
@dvacca no problem :) thanks a lot :)

**Comment by dvacca** [comment]
@lotr [PR#80](https://github.com/onfido/onfido-java/pull/80) has just been merged. Could you please try to rebase your branch on master to see if that's effective? Thanks

**Comment by lotr** [comment]
@dvacca rebased :)

**Review by dvacca — APPROVED** [review]

**Comment by lotr** [comment]
@dvacca I can't merge it, insufficient rights (just saying :) )

**Pull request merged**
